export const PROJECTS_DATA = [
  {
    id: "barakah",
    name: "Barakah",
    domain: "barakah-platform.vercel.app",
    title: "Barakah - Compare Groceries, Shop Smarter",
    subtitle:
      "A platform where consumers can compare grocery prices of offline shops in their area. It encourages fair pricing and helps users find the best deals, saving them money and promoting transparency in the grocery market.",
    link: "https://barakah-platform.vercel.app/",
    linkLabel: "View Project",
    link2: "https://github.com/mdraihan27/barakah",
    link2Label: "GitHub Repo",
    tags: ["React", "FastAPI", "MongoDB", "Cloudinary", "Tailwind CSS"],
    preview: "/assets/images/projects/barakah/barakah-1.png",
    images: Array.from({ length: 24 }, (_, i) => ({
      src: `/assets/images/projects/barakah/barakah-${i + 1}.png`,
      alt: `Barakah Screenshot ${i + 1}`,
    })),
  },
  {
    id: "maildoor",
    name: "MailDoor",
    domain: "maildoor.raihanhossen.work",
    title: "MailDoor - Effortless SMTP Mailing API",
    subtitle:
      "A simple SMTP-based mailing service that lets you bypass DigitalOcean's blockage of SMTP mail sending and easily send mails to your users using your app password.",
    link: "https://maildoor.raihanhossen.work/",
    linkLabel: "View Project",
    link2: "https://github.com/mdraihan27/maildoor",
    link2Label: "GitHub Repo",
    tags: ["Next.js", "Express.js", "Nodemailer", "MongoDB"],
    preview: "/assets/images/projects/maildoor/maildoor-1.png",
    images: Array.from({ length: 7 }, (_, i) => ({
      src: `/assets/images/projects/maildoor/maildoor-${i + 1}.png`,
      alt: `MailDoor Screenshot ${i + 1}`,
    })),
  },
  {
    id: "everything-image",
    name: "Everything Image",
    domain: "everything-image.tech",
    title: "Everything Image - All-in-One Image Suite",
    subtitle:
      "The ultimate tool for quick image fixes. Easily convert, compress, crop, resize, edit, remove backgrounds, add watermarks, overlay text, blur, and enhance resolution — all in one place.",
    link: "https://everything-image.tech/",
    linkLabel: "View Project",
    link2: "https://github.com/mdraihan27/everything-image",
    link2Label: "GitHub Repo",
    tags: ["Next.js", "Tailwind CSS", "Canvas API", "WebAssembly"],
    preview: "/assets/images/projects/everything-image/everything-image-1.png",
    images: [
      { src: "/assets/images/projects/everything-image/everything-image-1.png", alt: "Landing Page" },
      { src: "/assets/images/projects/everything-image/everything-image-2.png", alt: "Add Text Page" },
      { src: "/assets/images/projects/everything-image/everything-image-3.png", alt: "Convert Page" },
      { src: "/assets/images/projects/everything-image/everything-image-4.png", alt: "Pro Editor Page" },
      { src: "/assets/images/projects/everything-image/everything-image-5.png", alt: "Add Watermark Page" },
      { src: "/assets/images/projects/everything-image/everything-image-6.png", alt: "Crop & Resize Page" },
      { src: "/assets/images/projects/everything-image/everything-image-7.png", alt: "About Page" },
    ],
  },
  {
    id: "ballotguard",
    name: "Ballotguard",
    domain: "ballotguard.vercel.app",
    title: "Ballotguard - Secure Online Voting System",
    subtitle:
      "The perfect online voting system. Enforces single person single vote principle by sending a private voting link to each voter's email. Supports open elections operating via public links as well.",
    link: "https://ballotguard.vercel.app/",
    linkLabel: "View Project",
    link2: "https://github.com/orgs/ballotguard/repositories",
    link2Label: "GitHub Org",
    tags: ["Next.js", "Spring Boot", "Tailwind", "MongoDB", "Spring Security"],
    preview: "/assets/images/projects/ballotguard/ballotguard-2.png",
    images: [
      { src: "/assets/images/projects/ballotguard/ballotguard-2.png", alt: "Landing Page" },
      { src: "/assets/images/projects/ballotguard/ballotguard-3.png", alt: "Signup Page" },
      { src: "/assets/images/projects/ballotguard/ballotguard-4.png", alt: "Dashboard Page" },
      { src: "/assets/images/projects/ballotguard/ballotguard-5.png", alt: "Election View" },
      { src: "/assets/images/projects/ballotguard/ballotguard-6.png", alt: "Ballot Creation" },
      { src: "/assets/images/projects/ballotguard/ballotguard-7.png", alt: "Vote Verification" },
      { src: "/assets/images/projects/ballotguard/ballotguard-8.png", alt: "Live Tallying" },
      { src: "/assets/images/projects/ballotguard/ballotguard-9.png", alt: "Voter List" },
      { src: "/assets/images/projects/ballotguard/ballotguard-10.png", alt: "Security Tokens" },
      { src: "/assets/images/projects/ballotguard/ballotguard-11.png", alt: "Admin Panel" },
      { src: "/assets/images/projects/ballotguard/ballotguard-12.png", alt: "Analytics" },
      { src: "/assets/images/projects/ballotguard/ballotguard-13.png", alt: "Audit Trail" },
      { src: "/assets/images/projects/ballotguard/ballotguard-14.png", alt: "Results Breakdown" },
    ],
  },
  {
    id: "neuraletter",
    name: "Neuraletter",
    title: "Neuraletter - AI-Native Newsletter Workspace",
    subtitle:
      "An AI-native newsletter workspace that lets you compose, iterate, and ship issues with a cinematic, distraction-free editor. Crafted to feel like a design tool, but moves at the speed of code.",
    link: null,
    linkLabel: null,
    link2: "https://github.com/orgs/densware/repositories",
    link2Label: "GitHub Repos",
    tags: [
      "Next.js",
      "FastAPI",
      "Mistral AI",
      "PostgreSQL",
      "DigitalOcean",
      "Nginx",
      "Tailwind CSS",
    ],
    preview: "/assets/images/projects/neuraletter/neuraletter-1.png",
    images: Array.from({ length: 9 }, (_, i) => ({
      src: `/assets/images/projects/neuraletter/neuraletter-${i + 1}.png`,
      alt: `Neuraletter Screenshot ${i + 1}`,
    })),
  },
];
